title: Zhirong Chen
url: "https://rong-hash.github.io"
baseurl: ""

markdown: kramdown
# ins_logo: "./Illinois_Block_I.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/rong-hash/rong-hash.github.io"
footer_text: "Page design by Zhirong Chen"

favicon: true
favicon_location: "favicon.ico"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Resume"
   link: "resume.pdf"
 - name: "Project"
   link: "zinix"
   link: "crimemap"
   link: "project"
 - name: "Contact"
   link: "contact"




remote_theme: ankitsultana/researcher@gem
