title: Zhirong Chen
url: "https://rong-hash.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/rong-hash/rong-hash.github.io"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Resume"
   link: "resume.pdf"
 - name: "Project"
   link: "project"
   link: "zinix"
   link: "crimemap"
 - name: "Contact"
   link: "contact"




remote_theme: ankitsultana/researcher@gem
